### ISSUE TITLE
Different non-linearity in controller

### ISSUE THREAD

**Issue by johny-c** [viking-sudo-rm/StackNN#27]
Hi all, thank you for publishing your code. 
I have a question regarding the non-linearity in the output layer of the controller. In their paper, Grefenstette et. al. use sigmoid for the pop and push signals and tanh for the value and output vectors. In your code, you use sigmoids for all outputs. Is that on purpose? Did you experiment with tanh?

**Comment by viking-sudo-rm** [comment]
Hi @johny-c,

Thanks for bringing this to our attention! I was actually unaware that Grefenstette used tanh, so I don't know what would be different. Maybe having negative values could be beneficial? I will bring this up in our next meeting. If you're interested in using the tanh variant, it should be a quick change to the `Struct` implementation.

**Comment by viking-sudo-rm** [comment]
Update: we've adapted the control scheme somewhat in anticipation of our upcoming paper at ACL BlackBox 2019.

The logic that decides these nonlinearities is now in https://github.com/viking-sudo-rm/StackNN/blob/master/control_layer/control_layer.py.
