### ISSUE TITLE
Code Readability Improvements

### ISSUE THREAD

**Issue by viking-sudo-rm** [viking-sudo-rm/StackNN#5]
Over the past couple months, I've written down some notes about ways to clean up the StackNN code. 

I think having clean code is important for several reasons. Firstly, it makes it much easier for external users to interact our code, which helps with reproducibility and follow-up experiments. This is timely given that we are about to publish. Additionally, having organized code and documentation lets new members of CLAY get up to speed quickly in the next semester. Another plus of having a clean code base is that we may be able to submit a pull request to integrate StackNN with `pytorch.contrib`!

With all of these concerns in mind, I have several suggestions for ways that we can clean up the existing code base. We should discuss which of these refactorings are the easiest/most important, as well as whether anything is missing.

### Standardizing Class Names with Paper Terminology
* The `Controller` hierarchy should be renamed to `Model`. These classes don’t actually affect the nature of the controller being used, but just the overall model architecture. The `SimpleStructNetwork` hierarchy should be renamed to `Controller`. These classes specify the architecture of the controller unit which interfaces with the stack.
* Drop “Abstract" from `AbstractController` (so it will end up just as `Model`).
* The `models.networks` subpackage should be made into a top-level package called `controllers`.

### Documentation Style
I propose we adapt documentation of functions and classes to follow the [Google Python style guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md) (what TensorFlow uses) or equivalent. This is somewhat subjective, based on what seems more readable/aesthetically pleasing. Converting current documentation comments to that format shouldn’t be much of an effort, and I think it is much more readable. It can be done on a frequency-of-use basis (Whenever encountering a file, we update its documentation). Example Google-style comment:

```python
def my_function(arg1, arg2):
  """One-line description of function.

  Additional in-depth description goes in paragraphs here.

  Args:
    arg1: This arg does this.
    arg2: This arg does this.

  Returns:
    Always None.
  """
  return None
```

### Performance and Compatibility
* *Removing one-hot encodings.* In some cases, replacing one-hot encodings with embedding layers might yield decent increases in performance.
* *Newest PyTorch.* This would be nice so we could integrate new features from a rapidly evolving framework.
* *Python 3.* Not really a high priority, but something to consider given that Python 2 will be deprecated in 2020.

### Random Stuff
* Model and controller become required arguments of task constructor.
* Constructor kwargs to Model (Controller) should not be passed as kwargs to Controller (Network)
* Should we move tasks/configs.py out of tasks package and instead make it top-level?
* Cleaning up constructor arguments/default values. The task class hierarchies have default values for arguments at several layers. This can make it confusing where a value is being set. I propose that all values should only be specified at one layer. For most task parameters, this should probably be in the concrete class. If there is a set of parameters applying to all tasks, we can remove them from the concrete constructors and use an **args parameter in concrete to override them.
* nit: Change `Logger` to use `__enter__`/`__exit__` hooks instead of `__del__`. Or use built-in logging module.

**Comment by NoahAmsel** [comment]
I'm down to work on this stuff this week. I know having clean code made it so much easier to contribute to this so I definitely think it's worth the investment.

**Comment by viking-sudo-rm** [comment]
Cool. I'm also down to work on it this week.

**Comment by yidinghao** [comment]
Regarding the documentation: The current format for function documentation (at least in the functions that I've written) is the reST format, which is the format recommended by the [official Python style guide (PEP 287)](https://www.python.org/dev/peps/pep-0287/). It's also readable by several code editors and documentation generators, such as [Sphinx](http://www.sphinx-doc.org/en/master/index.html), which is the reason it was recommended as the official Python format.

[Here](http://daouzli.com/blog/docstring.html) is a comparison of various docstring formats

**Comment by viking-sudo-rm** [comment]
Okay, I'm down to table that point then. I still think renaming the class names (Model, Controller, etc.) to be consistent with the paper would be pretty beneficial.

@NoahAmsel would you be down to take the renaming on? Otherwise I can do it.
